### ISSUE TITLE
explain to Hogg the fork switch

### ISSUE THREAD

**Issue by davidwhogg** [andycasey/AnniesLasso#2]
@andycasey how did you switch things to it went from your repo being a fork of mine to mine being a fork of yours?  Was that a "setting" change in both repos?  Or what?  It seems like it must be a github change (not a git change).  Anyway, both I and @dfm want to know.

**Comment by andycasey** [comment]
You're right: it's a GitHub change, not a git change. I googled around on how to de-fork my repository and it could only be done if I deleted this repository, created a new one and pushed my local copy. But that would eradicate any existing issues, wiki, etc. 

Instead you can email support@github.com and ask them to de-fork a repository. I pointed them to davidwhogg/annieslasso/issues/1 and asked if they could de-fork andycasey/annieslasso, and then they went one step further and turned yours into a fork of mine.

**Comment by davidwhogg** [comment]
That is evil and brilliant.
