### ISSUE TITLE
Continuum

### ISSUE THREAD

**Issue by andycasey** [andycasey/AnniesLasso#22]
Re-normalize continuum for all stars (training and test), according to the Ness-ish method.

**Comment by davidwhogg** [comment]
We are going to fit sines and cosines; to be discussed.

**Comment by davidwhogg** [comment]
Unfortunately this has to happen before we train with Lambda and all 17 labels!

**Comment by davidwhogg** [comment]
Here's the deal:

- set `L = 5000 #A` or so.
- make a design matrix that has `1`s in the first column, and then, in the subsequent columns:
```
np.array([[np.cos(k * lambda / L), np.sin(k * lambda / L)] for k in range(1,K+1)]).reshape(whatever)
```
- start with K=5 (say) and see how it goes.
- Do curvefit using the correct `ivar` but using only the @mkness-identified continuum pixels.
- Treat each third of the data independently, but use exactly the same inputs for the design matrix.
- Trust me.

**Comment by andycasey** [comment]
Aight, will do this now. By: "treat each third of the data independently", do you mean that because of the APOGEE CCDs, right? I was going to include a `regions` argument to specify whichever sections to be treated separately.

**Comment by davidwhogg** [comment]
Yes, each CCD separately.
