### ISSUE TITLE
Implement wavelength censoring

### ISSUE THREAD

**Issue by andycasey** [andycasey/AnniesLasso#23]
Should this be on vectorizer terms or label names? If it were on label names (e.g., [Al/H]) such that any cross terms with [Al/H] would also be zero. Which conceptual filter were you talking about @davidwhogg: label names or terms or both?

**Comment by davidwhogg** [comment]
label names!

**Comment by davidwhogg** [comment]
excited about this closure!

**Comment by andycasey** [comment]
It was fun to put in! I can explain the implementation details next time we chat, but they are user-friendly.

**Comment by davidwhogg** [comment]
I will try to call today. Also, my nucleosynthesis code works completely now!
