### ISSUE TITLE
Optimization issue when training regularized Cannon models

### ISSUE THREAD

**Issue by andycasey** [andycasey/AnniesLasso#24]
The following image suggests that the optimization is not converging during the training phase for regularization models with high Lambda values.

![image](https://cloud.githubusercontent.com/assets/504436/11830826/87d2fa0e-a376-11e5-806f-fe4912e398a9.png)

The problem appears to be unrelated to `ftol` or `xtol`. The above figure was using default `ftol` and `xtol`. If the tolerance is decreased (to `3e-5`) the same behaviour remains for a single line:
![image](https://cloud.githubusercontent.com/assets/504436/11831580/76d185ca-a37d-11e5-966f-f6bec1fdc9a3.png)

I think this bug is fixed now: Here's the same line in a 17-label model using default optimization tolerances:

![image](https://cloud.githubusercontent.com/assets/504436/11831630/03127e90-a37e-11e5-836f-26bdb90420b7.png)

And here are 28 pixels in a 3-label model:
![image](https://cloud.githubusercontent.com/assets/504436/11833694/475a2804-a393-11e5-982f-42c0c10bfdb4.png)

I also updated the code to allow for the initial `theta` to be provided, and that initial theta is passed on between successive steps of `Lambda`. And I've done a bunch of tests (in a 3-label model and a 17-label model) since fixing the bug, and `BFGS` works well until we hit high `Lambda`, at which point `BFGS` returns a warning. I've implemented the best-of-both: `BFGS` will run first, and if `BFGS` exits with a warning then Powell's method is run instead.

**Comment by andycasey** [comment]
for discussion;

![image](https://cloud.githubusercontent.com/assets/504436/11853152/43335af8-a40a-11e5-8090-4cfda3554a6f.png)


Produced at git hash `65f55485af9fa816834fe910cedbbb7f081f55b3`

**Comment by andycasey** [comment]
Two pixels, 3-label model with s^2 = 0 and fixed. Using Powell's method, theta initialized as {1,0,...0} with no theta information passed between.

Thin line is `ftol=1e-4` and `xtol=1e-4`, thick lines are the same pixels with `ftol=1e-8` and `xtol=1e-8`.

![image](https://cloud.githubusercontent.com/assets/504436/11853687/6f91d838-a40d-11e5-9555-030e510bb3a7.png)

**Comment by andycasey** [comment]
![image](https://cloud.githubusercontent.com/assets/504436/11853801/125625f6-a40e-11e5-96bb-b779c9a01aa6.png)

Same pixels. Thickest line is using BFGS + Powell w/ (`ftol=1e-4`, `xtol=1e-4`) when BFGS yields warning

**Comment by andycasey** [comment]
Same pixels. Left is a 3-parameter model, right is a 17-parameter model. The right hand side one isn't as well sampled because it's slightly more expensive (even with derivatives).

![image](https://cloud.githubusercontent.com/assets/504436/11859595/5b205dac-a43a-11e5-8e87-386099965180.png)

**Comment by davidwhogg** [comment]
I think this issue can probably be closed now, since it has branched into various other things.

**Comment by andycasey** [comment]
![image](https://cloud.githubusercontent.com/assets/504436/11863216/330e9fc4-a460-11e5-822e-12b9a348bd68.png)

Note that the few points at 10^2 only provide marginally worse model predictions when Lambda = 10^3. That is to say, the test scalar values do not rise sharply for those pixels. If scatter were not fixed at train time, I imagine the slightly poorer predictions for those few pixels would be encapsulated in the s^2 term for that pixel.

**Comment by andycasey** [comment]
![image](https://cloud.githubusercontent.com/assets/504436/11872639/70009844-a4a4-11e5-9b55-12c08410f4e1.png)

Mean of test scalars at a given Lambda. Also relevant to #27

**Comment by davidwhogg** [comment]
Branching to other issues
