### ISSUE TITLE
almost every pixel is masked for many training-set stars!

### ISSUE THREAD

**Issue by davidwhogg** [andycasey/AnniesLasso#35]
Here is an example: 2M06123730+4036001

...but there are many more.  What is going on?  How can ASPCAP give us "good" labels for a star that almost no pixel is good in any sub-visit.  Literally not one good measurement of any wavelength at all.

**Comment by davidwhogg** [comment]
Right now we have decided (arbitrarily) to ignore all persistence-related flags, but we made that shit up.

**Comment by mkness** [comment]
@andycasey which dimension of the array are you calling on to load the mask from?

**Comment by davidwhogg** [comment]
We are using the individual-visit masks; is that what you are asking?

**Comment by davidwhogg** [comment]
I'm closing this, because we have a new stacking working; this is out of scope.
