### ISSUE TITLE
Sparsity metrics for different Lambdas and scale factors

### ISSUE THREAD

**Issue by andycasey** [andycasey/AnniesLasso#37]

**Comment by andycasey** [comment]
@davidwhogg While calculating these sparsity metrics for a few models I made a plot you'll like. It shows the derivative dependence for a cross term (I just chose a random large theta index) for two regularized (Lambda = 10^3.5) models with different scale factors `f`.

![sf_dependence1](https://cloud.githubusercontent.com/assets/504436/12064543/816e57a0-afbd-11e5-888c-2c2e8fdc2842.png)
![sf_dependence2](https://cloud.githubusercontent.com/assets/504436/12064544/816f5f06-afbd-11e5-9d4c-e5bfb459da24.png)

I'm fitting individual spectra for #39 now.

**Comment by davidwhogg** [comment]
looks VERY good and just as we expect, no?

**Comment by andycasey** [comment]
shit yeah! it fucking blew my mind when I saw how clean it was. I didn't think it would work that well... 

(this post was brought to you by a comically large 1.5L bottle of champagne)

**Comment by andycasey** [comment]
In progress image of sparsity metrics are below. `S` is fraction of non-zero coefficients. Not all models are trained yet, but the behaviour is as expected.

![sparsity_progress](https://cloud.githubusercontent.com/assets/504436/12080249/feed18ce-b24c-11e5-899a-78facdb6cea6.png)

**Comment by davidwhogg** [comment]
COOL.  Semilogy, please, or loglog and plot Lambda rather than log10(Lambda)

**Comment by davidwhogg** [comment]
Once you have a version of this plot you are happy with:
- [ ] put it in the paper
- [ ] with a caption; and
- [ ] close this issue.

**Comment by andycasey** [comment]
This is how it will look (from 333b54b):

![sparsity](https://cloud.githubusercontent.com/assets/504436/12095162/c8e1d298-b304-11e5-8f0a-b7ce2bf25e8c.png)

**Comment by davidwhogg** [comment]
EExcellent

**Comment by andycasey** [comment]
![sparsity](https://cloud.githubusercontent.com/assets/504436/12149639/b79e4a86-b49c-11e5-9737-1cdec7b7f87c.png)
