### ISSUE TITLE
Should we support Python 2.x?

### ISSUE THREAD

**Issue by andycasey** [andycasey/AnniesLasso#42]
There are two reasons I've encountered so far that make me think we should not:

1. The `CannonModel` class uses [pickle](https://docs.python.org/2/library/pickle.html) to save and load objects. Python 3 has a newer pickling protocol for saving Python objects, which is incompatible with previous versions. For that reason, any model saved in Python 3 using the highest available protocol (which is the current default in our code base, for many reasons) will not be loadable in Python 2.x. Someone would have to load it in Python 3, then save it again using a lower protocol. The newer protocol has faster read/write times and **much** smaller file sizes.

2. See #40, although that is not strictly a 'Python 2' problem but more of an 'BLAS' problem which cannot be fixed by pure-Python code in Python 2.x.

@davidwhogg, @mkness: comments welcome!

**Comment by davidwhogg** [comment]
I think Python2.7 support is an enhanced goal, but I am happy to Python3.

**Comment by andycasey** [comment]
Executive decision: Python3 and Python2.7 will be supported in the sense that the code and its tests will be required to pass in both. But Python2.7 can have some weird multiprocessing behaviour in different environments (e.g., #40), so the motto will be "if in doubt, or you're having parallel issues, switch to Python 3".

**Comment by andycasey** [comment]
@adrn has solved this issue for us: https://github.com/adrn/shame

We just need to add 'shame' to the project requirements when we finally decide not to address Python 2.x issues.

**Comment by davidwhogg** [comment]
Looking forward to that day.
