### ISSUE TITLE
synchronize github with SDSS svn

### ISSUE THREAD

**Issue by davidwhogg** [andycasey/AnniesLasso#44]
we need to have the code duplicated within SDSS to become an official part of DR14.  Timescale for completion: mid-2016.

Also, it would be cool to make this very easy to maintain and update.

**Comment by andycasey** [comment]
We did this, but only through  pointing Holtz to the directory and an example script. An auto-synchronise feature looks unlikely for some time, so we will just have to point people to tagged  releases (or at worst, commit hashes).
