### ISSUE TITLE
actually set / choose fiducial f, Lambda for APOGEE DR12

### ISSUE THREAD

**Issue by davidwhogg** [andycasey/AnniesLasso#48]
we have everything we need to do this.  This is our major stumbling block for paper 0.

**Comment by davidwhogg** [comment]
once this is set, also deliver the data file to @davidwhogg

**Comment by andycasey** [comment]
I think the magic numbers are going to be:

`f = 2`
`Lambda = 10^3`

That yields a sparsity of ~20%, the chi^2 fits to the validation spectra show it to be a better model (indeed at the minimum for that scale factor), and the performance in recovering labels at low S/N is very comparable to an unregularized case. The `f = 2, Lambda = 10^3` model actually performs better for some labels at low S/N (logg, [Ni/H], [N/H]), but worse for others at S/N ~ 10. 

Now the question is: should we train a model with `f = 2`, `Lambda = 10^3` **without** fixed scatter and see how it performs?

**Comment by davidwhogg** [comment]
I consider this adopted.

Can you write this decision up in a clear, non-wrong paragraph into the paper, saying what tests we did but that we are setting this *heuristically*, and then close this issue?

The scatter point is a separate issue.

**Comment by davidwhogg** [comment]
Thinking about it:  NO, let's not fit for scatter -- let's stay with *convex* optimization.

But look at #31 and see if you agree.

**Comment by andycasey** [comment]
Will do -- I just ran the analysis for 150,000 spectra with this model.

It took 28 minutes.

**Comment by davidwhogg** [comment]
Make sure you also comment about speed in the paper!
