### ISSUE TITLE
re-starts at test time

### ISSUE THREAD

**Issue by davidwhogg** [andycasey/AnniesLasso#49]
Right now we do a single optimization at test time. This can't be right, since the optimization is non-convex.  Also, Anna Ho finds that for LAMOST there are wrong answers caused by local minima.  We should define a set of K initializations and start from all K, and choose the best answer (best in a likelihood sense).  This, unfortunately, is high priority...

**Comment by davidwhogg** [comment]
ps. Rix requested it by phone today, and rightly so.

**Comment by andycasey** [comment]
`K` need to be decided before analysing all 150,000 spectra again with the preferred regularized model. So I propose this, which is probably overkill:

1. The fiducial values (mean of all parameters in the training set).
2. The fiducial Teff and logg, with the 25th percentile of all abundances.
3. The fiducial Teff and logg, with the 75th percentile of all abundances.
4. The 25th percentile in Teff and logg, with the training set mean of all abundances.
5. The 25th percentile in Teff and logg, with the 25th percentile of all abundances.
6. The 25th percentile in Teff and logg, with the 75th percentile of all abundances.
7. The 75th percentile in Teff and logg, with the training set mean of all abundances.
8. The 75th percentile in Teff and logg, with the 25th percentile of all abundances.
9. The 75th percentile in Teff and logg, with the 75th percentile of all abundances.

**Comment by davidwhogg** [comment]
Happy!!
