### ISSUE TITLE
compute precisions and return formal errors

### ISSUE THREAD

**Issue by davidwhogg** [andycasey/AnniesLasso#51]
This critical

**Comment by andycasey** [comment]
Get online mofo

**Comment by davidwhogg** [comment]
wha?

**Comment by andycasey** [comment]
(Ness and I were waiting for you on Skype at the time, and we could see you were active on GitHub)

 Do you mean just returning formal errors from the covariance matrix at test time, or those formal errors plus some error model that we have built from our validation tests?

**Comment by davidwhogg** [comment]
Just the covariance matrix.

**Comment by andycasey** [comment]
Oh, great: well we already do that and save it to the result file at test-time. I'll put the formal errors as columns in the final table.

**Comment by davidwhogg** [comment]
For formal errors, there are the inverse-sqrts of the inverse covariance matrix diagonals, and there are sqrts of the covariance matrix diagonals.  We want the latter.
