### ISSUE TITLE
Ensure @arXiver will show our M15 abundance comparison when the paper goes on arXiv.

### ISSUE THREAD

**Issue by andycasey** [andycasey/AnniesLasso#52]

**Comment by davidwhogg** [comment]
To specify which figures you want to appear alongside your paper, please leave a comment in any .tex file before uploading to arXiv, as in this example: 

%@arxiver{fig1.pdf,fig4.png,fig15.eps}

Note: do *not* include the path to the figure (just the name and extension) – the arXiver code will find nested figures automatically. See the FAQ for more details!
