### ISSUE TITLE
Melissa to make Anna Ho's changes to tex

### ISSUE THREAD

**Issue by mkness** [andycasey/AnniesLasso#55]
Melissa needs to do this by COB Tuesday March 1.

**Comment by mkness** [comment]
I have done this and DHW has the marked up tex. Some things outstanding from Anna's email that should be addressed (either now or at respond to ref e.g. for point 2): 

1) Did not touch the Figure order (Figures are not referred to in order).
2) Units on plots - inconsistent in that sometimes there, sometimes not
3) Anna suggests stating we do not create ground truth we only propagate the training set (see below for more details).

**Comment by davidwhogg** [comment]
I won't close this issue because we have the three things @mkness lists as still open issues.

**Comment by davidwhogg** [comment]
no I am going to close  and open a new one.
