### ISSUE TITLE
Submit Annies Lasso paper 1

### ISSUE THREAD

**Issue by andycasey** [andycasey/AnniesLasso#59]
I have internet access again!

I've already submitted the preliminary manuscript data to AAS in their new system. (We will be reference AAS00008 -- the eighth manuscript in their new streamlined system.)

**Comment by davidwhogg** [comment]
Go ahead and submit; Rix comments can wait for respond-to-referee.  But maybe hold off on arXiv till we discuss?

**Comment by andycasey** [comment]
Should we wait for @dfm comments? I sent him a ping yesterday to see how much time he needed

**Comment by davidwhogg** [comment]
no, no waiting; he was warned.

**Comment by dfm** [comment]
plus... @dfm SEA :airplane: LAS :game_die:

**Comment by davidwhogg** [comment]
Sweet -- doubling your salary this weekend?

**Comment by dfm** [comment]
That's the plan!

**Comment by andycasey** [comment]
Red always wins!

Also: closing this because it paper 1 of Annies Lasso is now submitted to AAS (ApJ) and the arXiv (hopefully :00).

**Comment by davidwhogg** [comment]
Did you 59 it?

**Comment by andycasey** [comment]
Hahaha

I :02'd it. Stupid melbourne time delay.. I hope we are still up high!

**Comment by davidwhogg** [comment]
Good! I bet we will be 23rd
