### ISSUE TITLE
find or make a training set for GALAH

### ISSUE THREAD

**Issue by davidwhogg** [andycasey/AnniesLasso#64]
I think perhaps sven has already done this?  But what about detailed abundances?

**Comment by mkness** [comment]
1. Sven has a training set of 2.5K stars with 4 labels determined via the code SME (of teff, logg, Fe/H, alpha/Fe). All stars have a SNR > 50. These are K2 stars and clusters: all of these stars have been inspected by eye and cross-validation demonstrates there needs to be two training sets: one for giants and one for main sequence as the currently used quadratic model is insufficient to do both simultaneously. For individual abundances: The program SME will be used to determine the X/Fe for a set of stars (say 10K stars) which will then be used to make a model for The Cannon to then return the X/Fe for all GALAH stars. 
2. Individual abundance determination we can do now using APOGEE results: there are ~150 giants observed by GALAH in common with APOGEE. We can make a model with all APOGEE abundances using these. Although small, this set still should be sufficient to demonstrate now that we can put GALAH directly on the APOGEE scale and provide a set of X/Fe results.

**Comment by davidwhogg** [comment]
Good and good! How many of the 19 apogee abundances are expected to be measured by galah?
