### ISSUE TITLE
Dumb, slow, absolute convergence

### ISSUE THREAD

**Issue by andycasey** [andycasey/AnniesLasso#67]
Training is convex at any fixed `s^2`. We originally had two layers of optimization: we would optimize `s^2` on its own, then at a given `s^2` the coefficients would be determined (incorrectly by linear algebra). But we removed that because it was wrong for high orders/large matrices, and it was slow.

We should include a function that has different optimization behaviour, so that we can check things if we are ever worried about convergence:
- Optimize `s^2` by bisection over some plausible interval range of `[0, s^2_max]`, or some similarly slow yet trustworthy algorithm.
- At each `s^2` optimize `\theta` coefficients, using the last `\theta` coefficients determined in the previous `s^2` iteration as an initial guess (or the fiducial `[1, 0, ..., 0]`, whichever is a better initial guess for that `s^2`).

**Note:** this is not the recommended default behaviour; it should just be a utility function to ensure convergence.

**Comment by davidwhogg** [comment]
I thought we had dropped optimization of s^2 entirely?

**Comment by andycasey** [comment]
We did, but I thought one day it might be reawakened, in which case a dumb optimizer check would be useful.

**Comment by davidwhogg** [comment]
Indeed.
