### ISSUE TITLE
coefficients/theta and pixel variance

### ISSUE THREAD

**Issue by andycasey** [andycasey/AnniesLasso#7]
this is a nomenclature question for @davidwhogg:

when trained, a `CannonModel` currently has attributes `model.coefficients` and `model.scatter`.

I'm refactoring the code to calculate the inverse variances and use them in the right way, and in doing so I actually solve for `s^2`. Should `model.coefficients` and `model.scatter` be renamed, and if so, to what?
`model.theta` and `model.pixel_variance`? something else?

**Comment by davidwhogg** [comment]
It should *really* be called "intrinsic variance".  Or "s2" for consistency with the paper.  And yes on model.theta.

**Comment by andycasey** [comment]
I've settled on `s2` and `theta`
