### ISSUE TITLE
Fail test_cannon: AssertionError: False is not true

### ISSUE THREAD

**Issue by erwin0825** [andycasey/AnniesLasso#72]
All other tests returned ok except for test_cannon. I have tried updating all relevant modules. It did not solve the issue. 

The message reads:

FAIL: runTest (test_cannon.TestCannonModelRealistically)

----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_cannon.py", line 274, in runTest
    self.do_residuals()
  File "test_cannon.py", line 106, in do_residuals
    self.assertTrue(np.allclose(serial, parallel))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 2 tests in 26.585s

FAILED (failures=1)

**Comment by andycasey** [comment]
Use the code on the `develop` branch, not `master`.
