### ISSUE TITLE
Model fitting fails with TypeError: Improper input: N=17 must not exceed M=0

### ISSUE THREAD

**Issue by erwin0825** [andycasey/AnniesLasso#74]
I was trying to implement the Cannon using tutorial from The Cannon 1 and getting_started file here. I was successful at building the model with training set data. However, I had an error when I tried to fit the model on validity set data. The problem seems to originate from the  fit_spectrum function in cannon.py. 
running python 2.7.11, scipy 0.17.1, AnniesLasso from develop branch. 

```
import AnniesLasso.vectorizer as v
from AnniesLasso.vectorizer import NormalizedPolynomialVectorizer as NPV
from AnniesLasso.vectorizer.polynomial import terminator
# No regularization
model.regularization = 0
# Specify the vectorizer
terms = terminator(labels_noID, 2)
model.vectorizer = NPV(label_set, terms)
# train model
model.train()
# retrain model according to Hogg heuristic
model._set_s2_by_hogg_heuristic()
model.train()
# fit model with validity set data
# va_flux and va_ivar are of shape (1358, 8575)
validation_set_labels = model.fit(va_flux, va_ivar)
# error
```

2016-06-13 11:02:53,207 [INFO    ] Fitting 1358 spectra
2016-06-13 11:02:53,215 [ERROR   ] Exception within wrapped function
Traceback (most recent call last):
  File "/usr/users/bchen/anaconda2/lib/python2.7/site-packages/AnniesLasso/utils.py", line 115, in **call**
    result = self.f(_(list(x) + self.args), *_self.kwds)
  File "/usr/users/bchen/anaconda2/lib/python2.7/site-packages/AnniesLasso/cannon.py", line 441, in _fit_spectrum
    op_labels, cov = op.curve_fit(*_kwds)
  File "/usr/users/bchen/anaconda2/lib/python2.7/site-packages/scipy/optimize/minpack.py", line 651, in curve_fit
    res = leastsq(func, p0, args=args, full_output=1, *_kwargs)
  File "/usr/users/bchen/anaconda2/lib/python2.7/site-packages/scipy/optimize/minpack.py", line 380, in leastsq
    raise TypeError('Improper input: N=%s must not exceed M=%s' % (n, m))
TypeError: Improper input: N=17 must not exceed M=0

---

TypeError                                 Traceback (most recent call last)
<ipython-input-23-b48ff17b81f1> in <module>()
----> 1 validation_set_labels = model.fit(va_flux, va_ivar)

/usr/users/bchen/anaconda2/lib/python2.7/site-packages/AnniesLasso/model.pyc in wrapper(model, _args, *_kwargs)
     38         if not model.is_trained:
     39             raise TypeError("the model needs training first")
---> 40         return method(model, _args, *_kwargs)
     41     return wrapper
     42 

/usr/users/bchen/anaconda2/lib/python2.7/site-packages/AnniesLasso/cannon.pyc in fit(self, normalized_flux, normalized_ivar, initial_labels, model_lsf, model_redshift, full_output, *_kwargs)
    252         mapper = map if self.pool is None else self.pool.map
    253 
--> 254         labels, cov, metadata = zip(_mapper(f, zip(*args)))
    255         labels, cov = (np.array(labels), np.array(cov))
    256 

/usr/users/bchen/anaconda2/lib/python2.7/site-packages/AnniesLasso/utils.pyc in **call**(self, x)
    113     def **call**(self, x):
    114         try:
--> 115             result = self.f(_(list(x) + self.args), *_self.kwds)
    116         except:
    117             logger.exception("Exception within wrapped function")

/usr/users/bchen/anaconda2/lib/python2.7/site-packages/AnniesLasso/cannon.pyc in _fit_spectrum(normalized_flux, normalized_ivar, dispersion, initial_labels, vectorizer, theta, s2, model_lsf, model_redshift, **kwargs)
    439             kwds["p0"] += [5] # MAGIC
    440 
--> 441         op_labels, cov = op.curve_fit(**kwds)
    442         fvec = f(None, *op_labels)
    443 

/usr/users/bchen/anaconda2/lib/python2.7/site-packages/scipy/optimize/minpack.pyc in curve_fit(f, xdata, ydata, p0, sigma, absolute_sigma, check_finite, bounds, method, *_kwargs)
    649         # Remove full_output from kwargs, otherwise we're passing it in twice.
    650         return_full = kwargs.pop('full_output', False)
--> 651         res = leastsq(func, p0, args=args, full_output=1, *_kwargs)
    652         popt, pcov, infodict, errmsg, ier = res
    653         cost = np.sum(infodict['fvec'] *\* 2)

/usr/users/bchen/anaconda2/lib/python2.7/site-packages/scipy/optimize/minpack.pyc in leastsq(func, x0, args, Dfun, full_output, col_deriv, ftol, xtol, gtol, maxfev, epsfcn, factor, diag)
    378     m = shape[0]
    379     if n > m:
--> 380         raise TypeError('Improper input: N=%s must not exceed M=%s' % (n, m))
    381     if epsfcn is None:
    382         epsfcn = finfo(dtype).eps

TypeError: Improper input: N=17 must not exceed M=0

**Comment by andycasey** [comment]
Hi @erwin0825,

This looks like it could be a recent bug that I accidentally introduced when implementing redshift- and broadening-fitting at test time.

Could you email me at arc@ast.cam.ac.uk with the training set data and complete code (or as much as possible) that reproduces the problem?

**Comment by andycasey** [comment]
Hi @erwin0825, it looks like this isn't related to the new changes I introduced.

I think it is because the input spectrum for one star contains "no information": either every pixel has a zero inverse variance, or the flux in the pixel is non-finite. Thus if `sum(np.isfinite(flux) * (ivar > 0)) == 0` for a spectrum, there is no information in that star. I've just pushed a commit that should "fix" this issue by returning `NaN`s for labels, and there will be a `message` in the metadata dictionary that explains there was no information for that star. This is much more preferable to just falling over completely, particularly if there are many stars being analysed at once.

Can you let me know if this fixes your issue?

**Comment by erwin0825** [comment]
Yes. Thank you!
