### ISSUE TITLE
Getting Started tutorial data

### ISSUE THREAD

**Issue by wylie22s** [andycasey/AnniesLasso#80]
Hi!
I am really interested in using the Cannon. I'd like to try the getting started tutorial which trains a model using APOGEE DR14 spectra and ASPCAP labels. However, it seems that the data for the tutorial is missing. The line: wget zenodo-link #TODO  doesn't download anything.
Is it possible to get the tutorial data ?
Thanks so much!

**Comment by davidwhogg** [comment]
whoops. I am sorry about this; and sorry for slow response. I am hereby pinging @andycasey
